export enum CurrencyType {
    EUR = 'EUR',
    USD = 'USD',
    XOF = 'XOF',
    XAF = 'XAF',
    GBP = 'GBP',
    JPY = 'JPY',
    CHF = 'CHF',
    CAD = 'CAD',
    AUD = 'AUD',
    CNY = 'CNY',
    HKD = 'HKD',
    SGD = 'SGD',
    INR = 'INR',
    RUB = 'RUB',
    BRL = 'BRL',
    ZAR = 'ZAR',
    NGN = 'NGN',
    GHS = 'GHS',
    KES = 'KES',
    MAD = 'MAD',
    EGP = 'EGP',
    TND = 'TND',
    AED = 'AED',
    SAR = 'SAR',
    MXN = 'MXN',
    KRW = 'KRW',
    NZD = 'NZD',
    SEK = 'SEK',
    NOK = 'NOK',
    DKK = 'DKK',
  }
  
  // Descriptions des devises
  export const currencyDescriptions: Record<CurrencyType, string> = {
    [CurrencyType.EUR]: 'Euro',
    [CurrencyType.USD]: 'US Dollar',
    [CurrencyType.XOF]: 'CFA Franc BCEAO',
    [CurrencyType.XAF]: 'CFA Franc BEAC',
    [CurrencyType.GBP]: 'British Pound',
    [CurrencyType.JPY]: 'Japanese Yen',
    [CurrencyType.CHF]: 'Swiss Franc',
    [CurrencyType.CAD]: 'Canadian Dollar',
    [CurrencyType.AUD]: 'Australian Dollar',
    [CurrencyType.CNY]: 'Chinese Yuan',
    [CurrencyType.HKD]: 'Hong Kong Dollar',
    [CurrencyType.SGD]: 'Singapore Dollar',
    [CurrencyType.INR]: 'Indian Rupee',
    [CurrencyType.RUB]: 'Russian Ruble',
    [CurrencyType.BRL]: 'Brazilian Real',
    [CurrencyType.ZAR]: 'South African Rand',
    [CurrencyType.NGN]: 'Nigerian Naira',
    [CurrencyType.GHS]: 'Ghanaian Cedi',
    [CurrencyType.KES]: 'Kenyan Shilling',
    [CurrencyType.MAD]: 'Moroccan Dirham',
    [CurrencyType.EGP]: 'Egyptian Pound',
    [CurrencyType.TND]: 'Tunisian Dinar',
    [CurrencyType.AED]: 'UAE Dirham',
    [CurrencyType.SAR]: 'Saudi Riyal',
    [CurrencyType.MXN]: 'Mexican Peso',
    [CurrencyType.KRW]: 'South Korean Won',
    [CurrencyType.NZD]: 'New Zealand Dollar',
    [CurrencyType.SEK]: 'Swedish Krona',
    [CurrencyType.NOK]: 'Norwegian Krone',
    [CurrencyType.DKK]: 'Danish Krone',
  };
  
  // Symboles des devises
  export const currencySymbols: Record<CurrencyType, string> = {
    [CurrencyType.EUR]: '€',
    [CurrencyType.USD]: '$',
    [CurrencyType.XOF]: 'CFA',
    [CurrencyType.XAF]: 'FCFA',
    [CurrencyType.GBP]: '£',
    [CurrencyType.JPY]: '¥',
    [CurrencyType.CHF]: 'CHF',
    [CurrencyType.CAD]: 'C$',
    [CurrencyType.AUD]: 'A$',
    [CurrencyType.CNY]: '¥',
    [CurrencyType.HKD]: 'HK$',
    [CurrencyType.SGD]: 'S$',
    [CurrencyType.INR]: '₹',
    [CurrencyType.RUB]: '₽',
    [CurrencyType.BRL]: 'R$',
    [CurrencyType.ZAR]: 'R',
    [CurrencyType.NGN]: '₦',
    [CurrencyType.GHS]: 'GH₵',
    [CurrencyType.KES]: 'KSh',
    [CurrencyType.MAD]: 'د.م.',
    [CurrencyType.EGP]: 'E£',
    [CurrencyType.TND]: 'DT',
    [CurrencyType.AED]: 'د.إ',
    [CurrencyType.SAR]: '﷼',
    [CurrencyType.MXN]: 'Mex$',
    [CurrencyType.KRW]: '₩',
    [CurrencyType.NZD]: 'NZ$',
    [CurrencyType.SEK]: 'kr',
    [CurrencyType.NOK]: 'kr',
    [CurrencyType.DKK]: 'kr',
  };